### PR TITLE
Remove TFLite

### PR DESCRIPTION
**Pull request by regisss**
Remove references to TFLite and add a note about recommending Optimum as the tool to use for exporting models to TFLite.

### CODE REVIEW

**Comment by regisss** [comment]
@pcuenca Let me know if there is anything else to do regarding removing references to TFLite :slightly_smiling_face:

**Review by pcuenca — APPROVED** [review]
Thank you!

There's this placeholder function: https://github.com/huggingface/exporters/blob/57115034cb176f08a10b26772ccbf9e44d52a22d/src/exporters/coreml/convert.py#L627

which is being invoked from: https://github.com/huggingface/exporters/blob/main/src/exporters/coreml/convert.py#L689

If you could remove those references that'd be great; otherwise we can do it in a new PR.

**Comment by regisss** [comment]
It should be good now

**Review by pcuenca — APPROVED** [review]
Thank you!

**Pull request merged**
